/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/views/About.vue')['default']
    Arrow: typeof import('./src/components/arrow.vue')['default']
    Bubbletext: typeof import('./src/components/bubbletext.vue')['default']
    Canvas: typeof import('./src/views/Canvas.vue')['default']
    Connect: typeof import('./src/views/Connect.vue')['default']
    Content: typeof import('./src/views/Content.vue')['default']
    Footer: typeof import('./src/views/Footer.vue')['default']
    HomeVideo: typeof import('./src/components/HomeVideo.vue')['default']
    HorizontalScroller: typeof import('./src/components/HorizontalScroller.vue')['default']
    Loading: typeof import('./src/views/Loading.vue')['default']
    Navbar: typeof import('./src/views/Navbar.vue')['default']
    QuickNavigationBox: typeof import('./src/components/QuickNavigationBox.vue')['default']
    Routelinks: typeof import('./src/components/Routelinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sundays: typeof import('./src/views/Sundays.vue')['default']
    Visit: typeof import('./src/views/Visit.vue')['default']
  }
}
