/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/views/Canvas.vue')['default']
    Content: typeof import('./src/views/Content.vue')['default']
    HomeVideo: typeof import('./src/components/HomeVideo.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Navbar: typeof import('./src/views/Navbar.vue')['default']
    QuickNavigationBox: typeof import('./src/components/QuickNavigationBox.vue')['default']
    Routelinks: typeof import('./src/components/Routelinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
